"""State definitions for Reporting Agent."""

from typing import Any, TypedDict


class ReportingState(TypedDict):
    """Workflow state for the reporting agent.

    Attributes:
        question: Original user question to be answered by the report.
        tool_result: Raw algorithm execution output from the upstream agent.
        tool_description: Description/name of the graph algorithm used.
        final_report: Final report text generated by the LLM.
    """

    question: str
    tool_result: Any
    tool_description: str
    final_report: str


__all__ = ["ReportingState"]
